# This is a basic workflow to help you get started with Actions

name: GitVersion

# Controls when the workflow will run
on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gitVersion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
          
      - name: Checkout
        run: git fetch --tags

      - name: Fetch master for GitVersion
        if: github.ref != 'refs/heads/main'
        run: git branch --create-reflog master origin/main
        
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
    
      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
